# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1177, 716)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 1151, 671))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Pictures/Group 15.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_cadastro = QtWidgets.QLabel(self.centralwidget)
        self.label_cadastro.setGeometry(QtCore.QRect(620, 10, 531, 81))
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(48)
        font.setBold(False)
        font.setWeight(50)
        self.label_cadastro.setFont(font)
        self.label_cadastro.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_cadastro.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cadastro.setObjectName("label_cadastro")
        self.lineEdit_nome = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nome.setGeometry(QtCore.QRect(632, 270, 211, 41))
        self.lineEdit_nome.setStyleSheet("QLineEdit{\n"
"    background-color: #cadbb7;\n"
"    border-radius:20px;\n"
"\n"
"}")
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.lineEdit_peso = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_peso.setGeometry(QtCore.QRect(900, 270, 211, 41))
        self.lineEdit_peso.setStyleSheet("QLineEdit{\n"
"    background-color: #cadbb7;\n"
"    border-radius:20px;\n"
"\n"
"}")
        self.lineEdit_peso.setObjectName("lineEdit_peso")
        self.label_cadastro_ = QtWidgets.QLabel(self.centralwidget)
        self.label_cadastro_.setGeometry(QtCore.QRect(640, 220, 181, 41))
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.label_cadastro_.setFont(font)
        self.label_cadastro_.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_cadastro_.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_cadastro_.setObjectName("label_cadastro_")
        self.label_peso = QtWidgets.QLabel(self.centralwidget)
        self.label_peso.setGeometry(QtCore.QRect(910, 230, 181, 41))
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.label_peso.setFont(font)
        self.label_peso.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_peso.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_peso.setObjectName("label_peso")
        self.label_cadastro_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_cadastro_2.setGeometry(QtCore.QRect(640, 360, 181, 41))
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.label_cadastro_2.setFont(font)
        self.label_cadastro_2.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_cadastro_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_cadastro_2.setObjectName("label_cadastro_2")
        self.lineEdit_idade = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_idade.setGeometry(QtCore.QRect(632, 410, 211, 41))
        self.lineEdit_idade.setStyleSheet("QLineEdit{\n"
"    background-color: #cadbb7;\n"
"    border-radius:20px;\n"
"\n"
"}")
        self.lineEdit_idade.setObjectName("lineEdit_idade")
        self.label_cadastro_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_cadastro_3.setGeometry(QtCore.QRect(910, 360, 181, 41))
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.label_cadastro_3.setFont(font)
        self.label_cadastro_3.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_cadastro_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_cadastro_3.setObjectName("label_cadastro_3")
        self.lineEdit_altura = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_altura.setGeometry(QtCore.QRect(900, 410, 211, 41))
        self.lineEdit_altura.setStyleSheet("QLineEdit{\n"
"    background-color: #cadbb7;\n"
"    border-radius:20px;\n"
"\n"
"}")
        self.lineEdit_altura.setObjectName("lineEdit_altura")
        self.pushButton_entrar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_entrar.setGeometry(QtCore.QRect(910, 540, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_entrar.setFont(font)
        self.pushButton_entrar.setStyleSheet("background-color: #cadbb7;\n"
"    border-radius:20px;\n"
"color:#485935;\n"
"font-size:20px;\n"
"font-weight:bold;\n"
"")
        self.pushButton_entrar.setObjectName("pushButton_entrar")
        self.label_cadastro_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_cadastro_4.setGeometry(QtCore.QRect(620, 70, 531, 81))
        font = QtGui.QFont()
        font.setFamily("NSimSun")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_cadastro_4.setFont(font)
        self.label_cadastro_4.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_cadastro_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_cadastro_4.setWordWrap(True)
        self.label_cadastro_4.setObjectName("label_cadastro_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1177, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_cadastro.setText(_translate("MainWindow", "Bem vindo."))
        self.label_cadastro_.setText(_translate("MainWindow", "Nome"))
        self.label_peso.setText(_translate("MainWindow", "Peso"))
        self.label_cadastro_2.setText(_translate("MainWindow", "Idade"))
        self.label_cadastro_3.setText(_translate("MainWindow", "Altura"))
        self.pushButton_entrar.setText(_translate("MainWindow", "Entrar"))
        self.label_cadastro_4.setText(_translate("MainWindow", "Preencha os campos a baixo para que seja calculado o IMC para você."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
